### ISSUE TITLE
Register API for retrieving Party list by new PartyUUIDs

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-register#154]
### Description

Altinn 2 SBL Bridge has been extended with new API endpoint for getting a list of Party entities, by the new PartyUUID identifier.

This endpoint needs a proxy API in altinn-register same as the existing
`POST register/api/v1/parties/partylist`

Existing APIs for retrieving Party object should also be updated to include new mapping for the PartyUUID property to the Party model.

Model update will require publishing a new nuget package update for: `Altinn.Platform.Models`

### Additional Information

For SBL Bridge API implementation see: https://dev.azure.com/digdir/Altinn/_git/Altinn/pullrequest/6589

### Tasks

- [ ] Update existing Party model and mapping for existing APIs
- [ ] Expose new internal API endpoint for getting party list by a list of PartyUUIDs (incl. new SBL Bridge Client operation)
- [ ] Deploy nuget package update for Altinn.Platform.Models for the update

### Acceptance Criterias

- [ ] Same functional experience as existing partylist API: Possible to lookup a list of Parties based on their UUIDs
- [ ] Existing APIs exposing the Party model should now include the PartyUUID property

_No response_
