### ISSUE TITLE
Identify and configure necessary accesses for Register

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-register#185]
### Description
The Register application should be updated to access azure resources through workload identity.

#### Identified resources:
- [x] Read access to Platform KeyVault

### Tasks
- [x] Configure the necessary accesses through workload identity (helm chart)
    - [x] Service account
    - [x] Azure AD configuration?
- [x] Update the code to no longer use the kvSettings to access the KeyVault
- [x] QA
- [ ] Manual tests

### Acceptance criteria
- [ ] Register can access the platform key vault without the explicitly shared credentials.

**Comment by khanrn** [comment]
We need to modify the C# code below to integrate our solution to Register and implement a fallback mechanism as well as this is separate package now which could be used by some other services.

https://github.com/Altinn/altinn-authorization-utils/blob/main/src/Altinn.Authorization.ServiceDefaults/src/ServiceDefaults/Microsoft.Extensions.Hosting/AltinnServiceDefaultsExtensions.cs#L404

@sduaranc and I agreed to check it out later this week.

**Comment by khanrn** [comment]
Yes! We can unblock it! 👍

**Comment by Herskis** [comment]
@olebhansen Vår del er utført ser dere på manuell test og lukker saken til slutt!

**Comment by SandGrainOne** [comment]
@Herskis altinn-register ligger nå under Tilgangsinfo. Teamet til Espen og Rune.
