### ISSUE TITLE
TIlgjengeligjøre registerdata lokalt i Altinn 3

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-register#215]
### Description

Det er behov for å tilby registerdata lokalt i Altinn 3 for å kunne slå av Altinn 2 register og for å kunne sikre god ytelse i Altinn 3 frem til det slås av

```[tasklist]
### Analysis
- [ ] #171
- [ ] https://github.com/Altinn/altinn-register/issues/189
```

```[tasklist]
### Del epics
- [ ] https://github.com/Altinn/altinn-register/issues/235
- [ ] https://github.com/Altinn/altinn-register/issues/216
- [ ] https://github.com/Altinn/altinn-register/issues/214
- [ ] https://github.com/Altinn/altinn-register/issues/223
```
