### ISSUE TITLE
Eksportere registerdata i Altinn 2

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-register#216]
I første versjon av lokal kopi av Register i Altinn 3 så vil Altinn 2 fungere som kilde for Altinn 3. 

For dette skal funger må Altinn 2 publisere informasjon om endringer samt tilby API for å kunne hente ut all informasjon nødvendig fra Altinn 2. 

På et senere tidspunkt når Altinn 2 slås av vil dette erstattes med direkte integrasjon for de registrene som gjelder. 

## Akseptansekrav
- Altinn 2 må eksponere full Party informasjon som API på SBL Bridge
- Altinn 2 må eksponere informasjon om endringer har skjedd på Party
- Altinn 2 må eksponere rolleinformasjon for party. 

API Bridge

- [ ] https://github.com/Altinn/altinn-register/issues/218
- [ ] https://github.com/Altinn/altinn-register/issues/221
- [ ] https://github.com/Altinn/altinn-register/issues/222
- [ ] https://github.com/Altinn/altinn-register/issues/234
