### ISSUE TITLE
Sett opp jobb som lytter på innkommende meldinger på Party fra Altinn 2

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-register#240]
## Beskrivelse

Altinn 2 vil publisere et API hvor man kan hente ut informasjon om endringer på Party. Vi trenger å kjøre en jobb som løper gjennom dette API kontinuerlig og publiserer informasjon til kø som Altinn 3 komponenter kan lytte til

## Akseptansekrav
- [x] Jobb kjører i Azure
- [x] Jobb kjører kontinuerlig får å hente ut informasjon om endringer som Altinn 2 publiserer på inngående kø for Altinn register
- [x] Jobb må holde styr på hvor langt den er kommet
- [x] Jobb må kunne restartes
- [x] Publisere til intern kø for register 
- [x] Bruk mass transitt
- [x] Definer datamodell for "PartyChanged"  (partyUid, outboxId, timestamp) 
- [x] .Net applikasjon. Muligens implemenert som del av Register komponent

## Avklaring
-  Lande arkitektur på denne jobben
- ~~Er det alternativer til å bruke Azure Service Bus~~ 

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-register/issues/319
- [ ] Dokumenter jobb
- [x] Bygg jobb
- [ ] Sett opp infrastrutur
- [x] Sett opp bygg og deploy av jobb
```
