### ISSUE TITLE
Remove the term Platform from all projects and namespaces

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-register#9]
## Description 
`Altinn.Platform.Register` is repeated many places. This should be simplified to be `Altinn.Register`.

## Specification 
Folder structure where application projects are in a src folder and test projects are in a test folder.

src/Altinn.Register/Altinn.Register.csproj
test/Altinn.Register.Tests/Altinn.Register.Tests.csproj

Most of the structure is in place already, but the src/Register folder should be renamed to src/Altinn.Register.

## Tasks
- [x] Remove `Platform` from all namespaces
- [x] Restructure repository
- [x] Update github actions as needed
- [x] Update build pipelines in Azure DevOps
