### ISSUE TITLE
Upgrade the Register application to dotnet 7.

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-register#91]
### Description

It's about time to upgrade all platform applications again. This time we're bumping framework to version 7.0.

Documentation from Microsoft:
- https://learn.microsoft.com/en-us/aspnet/core/migration/60-70?view=aspnetcore-7.0&tabs=visual-studio
- https://learn.microsoft.com/en-us/dotnet/core/compatibility/7.0

The Register application is assummed to be the first one out so the issue is given some extra tasks related to learning about breaking changes and identify necessary changes if there are any.

### Tasks

- [x] Follow the instructions from Microsoft where applicable and upgrade the application.
- [x] Upgrade package references as needed.
- [x] Resolve compile time issues as they appear.
- [x] Run tests and perform as many tests as possible locally.

### Acceptance Criterias

- [x] Target framework for Register is "net7.0"
- [x] The application runs fine
- [x] All tests are green
- [x] Usecase tests are running green
