### ISSUE TITLE
Proper support for request cancelation

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-register#92]
## Description
All API should have a solid implementation to support request cancelation. If a client cancels their request, our server implementation should stop processing that request as early as possible. 

(Probably) All libraries being used to communicate with data storage services like Cosmos DB have support for request canceling using Cancelation tokens. This is currently not being used by any (I think) of the API in Altinn 3 because our API does not support it themselves.

Suggestion is to start easy by adding this to Register. It relies on HttpClient when forwarding requests to SblBridge. HttpClient does support request cancelation. SBLBridge does not have any explicit support for cancellation token. 

One big one would be canceling the upload or download of large attachments. There is an issue on this already, although that issue is more related to the frontend, the backend must also support it. Altinn/app-frontend-react#157 

## Considerations
Register might have dependencies that don't support cancellation tokens, these are not in scope for this issue to be updated.

## Tasks
-  [ ] Add support for cancellation tokens to the APIs
- [ ] QA
- [ ] Test
- [ ] Create issues for remaining platform components

## Acceptance criteria
- [ ] All APIs exposed by register should also accept a cancellation token ¨
- [ ] Regression tests are successful
